<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>dev.visdb.seesaw</groupId>
    <artifactId>seesaw-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <!-- adjust groupId for contrib modules -->
  <groupId>dev.visdb.seesaw.contrib</groupId>
  <artifactId>seesaw-contrib</artifactId>
  <packaging>pom</packaging>

  <name>${group_abbrev}</name>
  <modules>
    <module>lgooddatepicker</module>
    <module>simplevalidation</module>
  </modules>

  <properties>
    <group_abbrev>visdb.contrib</group_abbrev>

    <version.ldatepicker>11.2.1</version.ldatepicker>
    <!-- simplevalidation in seesaw-parent -->
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>dev.visdb.seesaw</groupId>
        <artifactId>seesaw-parent</artifactId>
        <version>${revision}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- simplevalidation is defined in seesaw-parent -->
      <dependency>
        <groupId>com.github.lgooddatepicker</groupId>
        <artifactId>LGoodDatePicker</artifactId>
        <version>${version.ldatepicker}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
<!-- vi: set sw=2 ts=8: -->
