<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>dev.visdb.seesaw</groupId>
  <artifactId>seesaw-parent</artifactId>
  <version>0.5.0</version>
  <packaging>pom</packaging>

  <name>${group_abbrev}:${project.artifactId}</name>

  <description>
    Seesaw library:
    Java swing database aware components.
    Supports multiple databases through plugins.
  </description>

  <url child.project.url.inherit.append.path="false">
    https://github.com/visdb-dev/seesaw
  </url>
  <scm child.scm.url.inherit.append.path="false" >
    <url>https://github.com/visdb-dev/seesaw</url>
  </scm>


<!--
<scm child.scm.connection.inherit.append.path="false" 
     child.scm.developerConnection.inherit.append.path="false" 
     child.scm.url.inherit.append.path="false">
    <connection>scm:git:git://://github.com</connection>
    <developerConnection>scm:git:ssh://://github.com</developerConnection>
    <url>https://github.com</url>
</scm>
-->

  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/visdb-dev/seesaw/issues</url>
  </issueManagement>

  <licenses>
    <license>
      <name>BSD 3-Clause</name>
      <url>https://spdx.org/licenses/BSD-3-Clause.html</url>
    </license>
  </licenses>

  <organization>
    <name>Raelity Engineering</name>
    <url>http://raelity.com</url>
  </organization>

  <developers>
    <developer>
      <name>Ernie Rael</name>
      <email>errael@raelity.com</email>
      <organization>Raelity Engineering</organization>
      <organizationUrl>http://raelity.com</organizationUrl>
    </developer>
  </developers>

  <modules>
    <module>seesaw</module>
    <module>seesaw-demo</module>
  </modules>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <group_abbrev>dev.visdb</group_abbrev>
    <snippet_path>${project.basedir}/src/test/java/snippet_files</snippet_path>


    <!-- Toolchain -->
    <version.maven>3.9.6</version.maven>
    <java-release>25</java-release>
    <!-- source/target for using frgaal -->
    <version.frgaal>25.0.0</version.frgaal>
    <java-source>24</java-source>
    <java-target>17</java-target>

    <!-- Dependencies -->
    <version.glazedlists>1.11.1203</version.glazedlists>
    <version.table-sort-header>1.0.1</version.table-sort-header>
    <version.google-guava>33.7.1-jre</version.google-guava>
    <version.util-lookup>1.0.0</version.util-lookup>
    <version.weak-event-bus-receiver>1.0.0</version.weak-event-bus-receiver>
    <version.jackson>3.2.2</version.jackson>
    <!--        Demo -->
    <version.log4j>2.26.1</version.log4j>
    <version.h2>2.5.250</version.h2>
    <version.java-getopt>1.0.13</version.java-getopt>
    <version.raelity-lib>1.2.0</version.raelity-lib>
    <version.simplevalidation>1.14.1</version.simplevalidation>
    <version.ldatepicker>11.2.1</version.ldatepicker>
    <!--
    <version.raelity_ldatepicker>11.2.300</version.ldatepicker>
    -->
    <version.logman>2.3.1</version.logman>
    <!--        Test -->
    <version.junit-jupiter>6.1.3</version.junit-jupiter>
    <version.assertj>3.27.7</version.assertj>
    <version.mockito>5.23.0</version.mockito>

    <!-- Plugins -->
    <version.versions-maven-plugin>2.21.0</version.versions-maven-plugin>
    <version.maven-enforcer-plugin>3.6.3</version.maven-enforcer-plugin>
    <version.maven-clean-plugin>3.5.0</version.maven-clean-plugin>
    <version.maven-resources-plugin>3.5.0</version.maven-resources-plugin>
    <version.maven-compiler-plugin>3.15.0</version.maven-compiler-plugin>
    <version.maven-surefire-plugin>3.5.6</version.maven-surefire-plugin>
    <version.maven-failsafe-plugin>3.6.0</version.maven-failsafe-plugin>
    <version.maven-jar-plugin>3.5.1</version.maven-jar-plugin>
    <version.maven-install-plugin>3.1.4</version.maven-install-plugin>
    <version.maven-site-plugin>4.0.0-M16</version.maven-site-plugin>
    <version.maven-assembly-plugin>3.8.0</version.maven-assembly-plugin>

    <!-- Publish Plugins -->
    <version.maven-deploy-plugin>3.1.4</version.maven-deploy-plugin>
    <version.central-publishing-maven-plugin>0.11.0</version.central-publishing-maven-plugin>
    <version.maven-source-plugin>3.4.0</version.maven-source-plugin>
    <version.maven-javadoc-plugin>3.12.0</version.maven-javadoc-plugin>
    <version.maven-gpg-plugin>3.2.8</version.maven-gpg-plugin>
    <version.flatten-maven-plugin>1.8.0</version.flatten-maven-plugin>

    <!-- Security -->
    <version.dependency-check-maven>13.0.0</version.dependency-check-maven>
  </properties>

  <dependencyManagement>
    <dependencies>
      <!-- Internal -->
      <dependency>
        <groupId>dev.visdb.seesaw</groupId>
        <artifactId>seesaw</artifactId>
        <version>${project.version}</version>
      </dependency>

      <!-- Shared deps -->
      <dependency>
        <groupId>com.raelity.3rdparty.com.glazedlists</groupId>
        <artifactId>glazedlists</artifactId>
        <version>${version.glazedlists}</version>
      </dependency>
      <dependency>
          <groupId>com.raelity.3rdparty.org.netbeans</groupId>
          <artifactId>util-lookup</artifactId>
          <version>${version.util-lookup}</version>
      </dependency>
      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>${version.google-guava}</version>
      </dependency>
      <dependency>
        <groupId>com.raelity.jdk</groupId>
        <artifactId>table-sort-header-renderer</artifactId>
        <version>${version.table-sort-header}</version>
      </dependency>
      <dependency>
        <groupId>com.raelity.lib</groupId>
        <artifactId>weak-event-bus-receiver</artifactId>
        <version>${version.weak-event-bus-receiver}</version>
      </dependency>
      <dependency>
        <groupId>tools.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <version>${version.jackson}</version>
      </dependency>
      <dependency>
        <groupId>tools.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>${version.jackson}</version>
      </dependency>
      <dependency>
        <groupId>tools.jackson.dataformat</groupId>
        <artifactId>jackson-dataformat-properties</artifactId>
        <version>${version.jackson}</version>
      </dependency>

      <!-- Demo-only deps -->
      <dependency>
        <groupId>com.h2database</groupId>
        <artifactId>h2</artifactId>
        <version>${version.h2}</version>
      </dependency>

      <dependency>
        <groupId>gnu.getopt</groupId>
        <artifactId>java-getopt</artifactId>
        <version>${version.java-getopt}</version>
      </dependency>

      <dependency>
        <groupId>com.raelity</groupId>
        <artifactId>raelity-lib</artifactId>
        <version>${version.raelity-lib}</version>
      </dependency>

      <dependency>
        <groupId>com.mastfrog</groupId>
        <artifactId>simplevalidation-standalone</artifactId>
        <version>${version.simplevalidation}</version>
      </dependency>

      <dependency>
        <groupId>com.github.lgooddatepicker</groupId>
        <artifactId>LGoodDatePicker</artifactId>
        <version>${version.ldatepicker}</version>
      </dependency>
      <!--
      <dependency>
          <groupId>com.raelity.3rdparty.com.github.lgooddatepicker</groupId>
          <artifactId>LGoodDatePicker</artifactId>
          <version>${version.raelity_ldatepicker}</version>
      </dependency>
      -->
      <dependency>
        <groupId>com.raelity.logman</groupId>
        <artifactId>logman-lib</artifactId>
        <version>${version.logman}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-jpl</artifactId>
        <version>${version.log4j}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <version>${version.log4j}</version>
      </dependency>
      <!-- Tests -->
      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter</artifactId>
        <version>${version.junit-jupiter}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
          <groupId>org.assertj</groupId>
          <artifactId>assertj-core</artifactId>
          <version>${version.assertj}</version>
          <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-core</artifactId>
        <version>${version.mockito}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-junit-jupiter</artifactId>
        <version>${version.mockito}</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>

        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>versions-maven-plugin</artifactId>
          <version>${version.versions-maven-plugin}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-clean-plugin</artifactId>
          <version>${version.maven-clean-plugin}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>${version.maven-resources-plugin}</version>
        </plugin>

        <!-- <arg>-proc:full</arg> needed starting jdk23  -->
        <!-- <arg>- -enable-preview</arg> -->
        <!-- Added from https://github.com/eppleton/frgaal -->
        <!-- -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${version.maven-compiler-plugin}</version>
          <dependencies>
            <dependency>                                    <!-- frgaal -->
              <groupId>org.frgaal</groupId>
              <artifactId>compiler-maven-plugin</artifactId>
              <version>${version.frgaal}</version>
            </dependency>
          </dependencies>
          <configuration>
            <generatedSourcesDirectory>${project.build.directory}/generated-sources/annotations</generatedSourcesDirectory>
            <compilerId>frgaal</compilerId>                 <!-- frgaal -->
            <source>${java-source}</source>
            <target>${java-target}</target>
            <compilerArgs>
              <arg>-Xlint:deprecation</arg>
              <!--
              -->
              <arg>-proc:full</arg>
            </compilerArgs>
            <!--
            <annotationProcessorPaths>
                <path>
                    <groupId>com.raelity.lib</groupId>
                    <artifactId>weak-event-bus-receiver</artifactId>
                    <version>${version.weak-event-bus-receiver}</version>
                </path>
                <path>
                    <groupId>com.raelity.3rdparty.org.netbeans</groupId>
                    <artifactId>util-lookup-bundle</artifactId>
                    <version>290</version>
                </path>
            </annotationProcessorPaths>
            -->
          </configuration>
        </plugin>

        <!-- need multi-release for frgaal -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${version.maven-jar-plugin}</version>
          <configuration>
            <archive>
              <manifestEntries>
                <Multi-Release>true</Multi-Release>
              </manifestEntries>
            </archive>
          </configuration>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${version.maven-surefire-plugin}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-failsafe-plugin</artifactId>
          <version>${version.maven-failsafe-plugin}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-install-plugin</artifactId>
          <version>${version.maven-install-plugin}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-site-plugin</artifactId>
          <version>${version.maven-site-plugin}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>${version.maven-assembly-plugin}</version>
        </plugin>

        <!-- OWASP (managed; executed only in -Psecurity-scan) -->
        <plugin>
          <groupId>org.owasp</groupId>
          <artifactId>dependency-check-maven</artifactId>
          <version>${version.dependency-check-maven}</version>
          <configuration>
            <nvdApiServerId>nvd</nvdApiServerId>
            <ossIndexServerId>ossindex</ossIndexServerId>
          </configuration>
        </plugin>

        <!-- antrun -->

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>3.0.0</version>
          <executions>
            <execution>
              <id>display-variable-value</id>
              <!-- Bind to a lifecycle phase, e.g., validate -->
              <phase>validate</phase>
              <goals>
                <goal>run</goal>
              </goals>
              <configuration>
                <target>
                  <echo message="snippet_path: ${snippet_path}" level="info"/>
                </target>
              </configuration>
            </execution>
          </executions>
        </plugin>

        <!-- Central Publishing (managed; executed only in -Prelease) -->

        <!-- Standard Deploy: Declared here so it's easy to configure everywhere -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-deploy-plugin</artifactId>
            <version>${version.maven-deploy-plugin}</version>
        </plugin>

        <!-- Maven Central Plugin: Handles portal uploads -->
        <plugin>
            <groupId>org.sonatype.central</groupId>
            <artifactId>central-publishing-maven-plugin</artifactId>
            <version>${version.central-publishing-maven-plugin}</version>
            <extensions>true</extensions>
            <configuration>
                <publishingServerId>central</publishingServerId>
                <!-- Make sure all modules OK before publishing -->
                <autoPublish>false</autoPublish>
                <waitUntil>validated</waitUntil>
            </configuration>
        </plugin>

        <!-- Required by Central: Source JAR generation -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <version>${version.maven-source-plugin}</version>
            <executions>
                <execution>
                    <id>attach-sources</id>
                    <goals>
                        <goal>jar-no-fork</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>

        <!-- Required by Central: Javadoc JAR generation -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <version>${version.maven-javadoc-plugin}</version>
            <configuration> <!-- EXTRA -->
              <release>${version.java}</release>
              <failOnError>false</failOnError>
              <sourcetab>4</sourcetab>
              <!-- - -snippet-path ${project.basedir}/src/test/java/snippet_files -->
              <additionalOptions>
                  <additionalOption>
                      --snippet-path ${snippet_path}
                  </additionalOption>
              </additionalOptions>
              <!-- TODO: don't supress "missing" -->
              <!-- TODO: don't supress "html" -->
              <doclint>all,-missing,-html</doclint>
              <links>
                <link>https://javadoc.io/static/com.raelity.3rdparty.com.glazedlists/glazedlists/${version.glazedlists}</link>
              </links>
            </configuration>
            <executions>
                <execution>
                    <id>attach-javadocs</id>
                    <goals>
                        <goal>jar</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>

        <!-- Required by Central: GPG Cryptographic Signing -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>${version.maven-gpg-plugin}</version>
            <executions>
                <execution>
                    <id>sign-artifacts</id>
                    <phase>verify</phase>
                    <goals>
                        <goal>sign</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>

        <!-- Resolves parent properties/variables before uploading -->
        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>flatten-maven-plugin</artifactId>
            <version>${version.flatten-maven-plugin}</version>
            <configuration>
              <flattenMode>oss</flattenMode>
              <pomElements>
                <name>expand</name>
              </pomElements>
            </configuration>
            <executions>
                <execution>
                    <id>flatten</id>
                    <phase>process-resources</phase>
                    <goals>
                        <goal>flatten</goal>
                    </goals>
                </execution>
                <execution>
                    <id>flatten.clean</id>
                    <phase>clean</phase>
                    <goals>
                        <goal>clean</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
      </plugins>
    </pluginManagement>

    <!-- Always-on enforcer -->
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>${version.maven-enforcer-plugin}</version>
        <executions>
          <execution>
            <id>enforce-versions</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>[${version.maven},)</version>
                </requireMavenVersion>
                <requireJavaVersion>
                  <version>[17,)</version>
                </requireJavaVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <profiles>

    <profile>
      <id>security-scan</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.owasp</groupId>
            <artifactId>dependency-check-maven</artifactId>
            <executions>
              <execution>
                <id>owasp-check</id>
                <phase>verify</phase>
                <goals>
                  <goal>check</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>release</id>
      <build>
        <plugins>
            <!-- 1. Turn off standard deployment entirely -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>

            <!-- 2. Activate all requirements for Central publishing -->
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
        </plugins>
      </build>
    </profile>

  </profiles>

</project>
